name: 🚀 Release
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - id: build
        uses: hoverkraft-tech/ci-github-publish/actions/deploy/jekyll@84d583ba7b357f9476707f54cf5419d630ae0145 # 0.26.2
        with:
          pages: |
            README.md
            CODE_OF_CONDUCT.md
            branding/README.md
          assets: |
            branding/*.png
          site-path: website

      - id: deploy
        uses: hoverkraft-tech/ci-github-publish/actions/deploy/github-pages@84d583ba7b357f9476707f54cf5419d630ae0145 # 0.26.2
        with:
          build-path: ${{ steps.build.outputs.build-path }}
